# Quindar GMAT source (simulation) Server Dockerfile
# Run command is /root/scripts/vnc_startup.sh
# Container can be accessed on port 6901 on browser

FROM centos:7
MAINTAINER quindar@audacy.space
LABEL vendor="Audacy"


# run system update & install utils
RUN yum -y update --setopt=tsflags=nodocs   && \
	yum -y install git wget nano curl make dos2unix && \
    yum clean all

##############################################################################

#**** install dependencies ***
RUN yum -y install zlib-devel libuuid-devel libmnl-devel gcc autoconf autoconf-archive autogen automake pkgconfig python tc python-yaml 
RUN yum install -y epel-release

#**** install openssl-devel ***
# Required for Python to use socket.io
RUN yum -y install openssl-devel

#**** install Python ****
# 
RUN yum -y groupinstall "Development Tools" && \
	yum -y install csh 						&& \
	yum -y install gtk3 gtk3-devel			&& \
	yum -y install freeglut-devel			&& \
	yum -y install cmake					&& \	
    yum -y update; yum clean all	

RUN wget https://www.python.org/ftp/python/3.4.3/Python-3.4.3.tar.xz
RUN tar xf Python-3.* 
RUN /bin/sh -c 'cd /Python-3.*; ./configure --enable-shared'
RUN /bin/sh -c 'cd /Python-3.*; LD_RUN_PATH=/usr/local/lib make'
RUN /bin/sh -c 'cd /Python-3.*; make altinstall'

RUN yum -y install python-pip 

#**** install xfce ****
ENV TERM xterm
RUN yum -y install epel-release && \
	yum --enablerepo=epel -y -x gnome-keyring --skip-broken groups install "Xfce"  && \
	yum -y groups install "Fonts" 

# Disable xfce-polkit
RUN rm /etc/xdg/autostart/xfce-polkit.desktop

#**** install vnc server ****
# VNC server port      : 5901
# start command        : /root/scripts/vnc_startup_gmat.sh
# default vnc password : vncpassword
# NoVNC web URL        : http://localhost:6901/vnc_auto.html?password=vncpassword

ENV DISPLAY :1
ENV NO_VNC_HOME /root/noVNC
ENV VNC_COL_DEPTH 24
ENV VNC_RESOLUTION 1280x1024
ENV VNC_PW vncpassword

RUN yum -y install tigervnc-server wget which net-tools && yum clean all -y

# copy files and make sure they are in unix format if building on windows host

COPY ./vnc/.vnc    /root/.vnc			
COPY ./vnc/.config /root/.config
COPY ./vnc/scripts /root/scripts
COPY ./vnc/Desktop /root/Desktop

RUN find /root/.vnc    -type f -exec dos2unix {} \;
RUN find /root/.config -type f -exec dos2unix {} \;
RUN find /root/scripts -type f -exec dos2unix {} \;
RUN find /root/Desktop -type f -exec dos2unix {} \;

RUN chmod +x   /etc/xdg/xfce4/xinitrc 	&& \
	chmod +x   /root/scripts/*.sh 		&& \
	chmod +x   /root/.vnc/xstartup 		&& \
	chmod 775  /root/Desktop/*	


#**** noVNC HTML5 based VNC viewer ****
#	
# https://github.com/kanaka/noVNC
#

RUN mkdir -p $NO_VNC_HOME/utils/websockify \
    && wget -qO- https://github.com/kanaka/noVNC/archive/v0.6.1.tar.gz | tar xz --strip 1 -C $NO_VNC_HOME \
    && wget -qO- https://github.com/kanaka/websockify/archive/v0.8.0.tar.gz | tar xz --strip 1 -C $NO_VNC_HOME/utils/websockify \
    && chmod +x -v /root/noVNC/utils/*.sh

COPY ./nginx/redirect.html $NO_VNC_HOME/index.html
RUN  /bin/dbus-uuidgen > /etc/machine-id


#**** install GMAT ****
# 
# deploy from github under /gmat
#

RUN  mkdir -p /gmat  
COPY gmat-update.sh /bin/gmat-update.sh
RUN  chmod a+x /bin/gmat-update.sh 
RUN  dos2unix  /bin/gmat-update.sh
RUN  ln -s /gmat /root/Desktop/GMAT

ENV  repo https://github.com/AudacySpace/quindar-gmat.git
RUN	 git clone --verbose $repo /gmat  
RUN  chmod a+x /gmat/application/bin/*
RUN  find      /gmat/application/bin -type f -exec dos2unix {} \;


#**** install npm ****
# npm is used for buildme.sh 
RUN yum -y install npm 

